AllCops:
  Exclude:
    - config.ru
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    - out/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  NewCops: enable

# use japanese :)
Style/AsciiComments:
  Enabled: false

# use method chain ( avoid use `end.compact` )
#
#   hoge.map { |item|
#     item.piyo
#   }.compact
Style/BlockDelimiters:
  Enabled: false

# rubocop v.0.51.0 is bugging...
#
#  def tweet(hash_tag: '#twitter')`
#    ...
#  end
Style/CommentedKeyword:
  Enabled: false

# no document
Style/Documentation:
  Enabled: false

# use `!!hoge`
Style/DoubleNegation:
  Enabled: false

# empty case is useful
#
#  case
#  when user.admin?
#    ...
#  when user.active?
#    ...
#  else
#    ...
#  end
Style/EmptyCaseCondition:
  Enabled: false

# my preference :)
Style/EmptyMethod:
  EnforcedStyle: expanded

# skip frozen string literal
Style/FrozenStringLiteralComment:
  Enabled: false

# use `-> {}` syntax
Style/Lambda:
  Enabled: false

# see Style/BlockDelimiters
Style/MultilineBlockChain:
  Enabled: false

# I feel `.zero?` difficult to understand...
Style/NumericPredicate:
  Enabled: false

# useful :)
Style/Semicolon:
  Exclude:
    - spec/**/*

# %w[a b c] or %i[a b c] ?
Style/SymbolArray:
  Enabled: false

# incompatible DSL
Layout/EmptyLinesAroundArguments:
  Enabled: false

# challenge!
Metrics/AbcSize:
  Max: 20
  Exclude:
    - app/models/authentication.rb

# incompatible DSL
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

# my preference :)
Metrics/LineLength:
  Max: 120

# challenge!
Metrics/MethodLength:
  Max: 20

# :bow:
Metrics/PerceivedComplexity:
  Max: 10

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
