production:
  clients:
    default:
      uri: <%= (ENV['MONGOLAB_URI'] || ENV['MONGO_URL'] || ENV['MONGODB_URI']) %>
      options:
        connect_timeout: 15
development:
  clients:
    default:
      database: togelack_development
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost:27017' %>
test:
  clients:
    default:
      database: togelack_test
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost:27017' %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
